### ISSUE TITLE
failed build with the new platform(p8) and libcec(p8)

### ISSUE THREAD

**Issue by kuboosoft** [UnitedRPMs/kodi-pvr-addons#1]
Well; l  told all in others issues; the currents pvr-addons isn't yet fully functional with p8 updates, until Kodi 17 (It will remove old code);  I will rename our "platform" to "platform-compat" and "libcec" to "libcec-compat". I will rebuilt kodi-platform with the  compat packages; maybe I need change some paths... Generally various peoples need the pvr-addons; example see free[ iptv](https://en.wikipedia.org/wiki/IPTV) chanels...

**Comment by sergiomb2** [comment]
hum I think the better was backport p8 updates

**Comment by kuboosoft** [comment]
p8 updates is welcome; but broke the pvr-addons. Ironic also gentoo have the same problem,  the solution was rename all; transitional but works :(

**Comment by sergiomb2** [comment]
where is gentoo solution ? , need see it , to give my opinion 
https://gitweb.gentoo.org/repo/gentoo.git/commit/media-plugins/kodi-pvr-hts?id=883f3b9e92b5f40e114683ffe3ac0f8a4c0c7456 
looks fixed

**Comment by kuboosoft** [comment]
@sergiomb2 Updated; I have problem to compile in Fedora 23... maybe you can find the problem :)

**Comment by sergiomb2** [comment]
well platform(p8) and libcec(p8) , have been update in F23 , the kodi-pvr-addons.spec (in this repo) is updated ?

**Comment by kuboosoft** [comment]
not yet; I stopped the pvr-addons since Kodi 16.0 in Fedora 23, maybe a gcc 5.x.x problem; I will share the log. strange but in Fedora 24 compiles fine...

**Comment by sergiomb2** [comment]
please update it , even if not build , to have the most recent sources.

**Comment by kuboosoft** [comment]
@sergiomb2 ok; I am checking now

**Comment by kuboosoft** [comment]
@sergiomb2 here the build log

Note: jsoncpp (official) the jsoncpp.pc (include dir) has bad path; was necessary install our compat jsoncpp06. I will report to bugzilla.
[build.log.zip](https://github.com/UnitedRPMs/kodi-pvr-addons/files/260554/build.log.zip)

**Comment by sergiomb2** [comment]
oh , I don't asked for build.log , I asked for last version of kodi-pvr-addons.spec , the https://github.com/UnitedRPMs/kodi-pvr-addons/blob/master/kodi-pvr-addons.spec is updated ?

**Comment by sergiomb2** [comment]
> Note: jsoncpp (official) the jsoncpp.pc (include dir) has bad path; was necessary install our compat jsoncpp06. I will report to bugzilla.

jsoncpp.pc have a bad path ? can you fix it ? if yes we should use jsoncpp-1.7.2-1+1.fc24 with the fix  , not make compats :)  straight forward

**Comment by sergiomb2** [comment]
it is all explained here 
https://aur.archlinux.org/packages/kodi-platform-git/

**Comment by kuboosoft** [comment]
Yes is updated; specific for kodi 16/16.1; the devel version only works with kodi 17

**Comment by sergiomb2** [comment]
No, I already build kodi-platform with p8-plataform , see my commit  ,
for pvr.argustv 
https://github.com/kodi-pvr/pvr.argustv/commit/bd208aa992eee2f38706d3b72b1c743738fa4312
and https://github.com/kodi-pvr/pvr.argustv/commit/1a64ac5e36a90cbe2c025003bb25aca5390d2ef1.patch
etc

**Comment by sergiomb2** [comment]
I can't finish it today , but all pvrs have the proper fix in github 
for example :
https://github.com/kodi-pvr/pvr.dvblink/commits/master
I did:  

```
wget https://github.com/kodi-pvr/pvr.dvblink/commit/28748d72f83e48e8f9470d01c2ec30b79b51de00.patch 
wget https://github.com/kodi-pvr/pvr.dvblink/commit/1031b8fd4bc66d6c49bf84250f10b69ff8c15e01.patch 
cat 800fb5e560f3a3258f08e0e2bd7c010c61e5a38d.patch 1dd5d43af06f7adc9114bde06d3583e57f3f9d15.patch > SOURCES/pvr.dvbviewer-p8.patch
```

Until now  it always hudokkow that fix it in 2 commits (writing Update to p8-platform), I copy the link and write wget add the link and at the end  .patch 
( wget https://github.com/kodi-pvr/pvr.dvblink/commit/1031b8fd4bc66d6c49bf84250f10b69ff8c15e01.patch )

**Comment by kuboosoft** [comment]
thanks, I will try this trick; is new for me :+1: If you like, I can attempt apply the patches :)
mmm the patch for pvr.hts and pvr.stalker failed! (temporally I disabled the patches hts and stalker); log in Fedora 23...
[build.log-p8.zip](https://github.com/UnitedRPMs/kodi-pvr-addons/files/262292/build.log-p8.zip)

**Comment by sergiomb2** [comment]
cool, go,od work !, I saw your commit , I'm testing it now ,
you can't comment %patch13 -p1 with #%patch13 , you need delete % 
so if you want be sure that is commented use #patch13

**Comment by sergiomb2** [comment]
I'm fixing the patches , please wait a little , for my commit thanks

**Comment by kuboosoft** [comment]
ok, thanks :+1:

**Comment by sergiomb2** [comment]
Done!,  we can delete plataform-compat , jsoncpp-compat  etc :-) , 
It compiles with plataform (p8), kodi-plataform  and jsoncpp-devel-1.7.2 (from fedora proper)

**Comment by sergiomb2** [comment]
I going publish kodi-plataform and kodi-pvr-addons in repo ! ok ? , I have good internet upload speed here

**Comment by kuboosoft** [comment]
:+1: thanks!! hey! no yet! please read the other issue; but you can include mpg123 ;)
