### ISSUE TITLE
pvr.mythtv crashes on activation

### ISSUE THREAD

**Issue by mjanser** [UnitedRPMs/kodi-pvr-addons#4]
When I install and activate the pvr.mythtv add-on for kodi, kodi crashes immediately. Is the latest version of the add-on in the repository? I also don't see where the sources are coming from for building the rpms.

If I build the add-on manually from https://github.com/kodi-pvr/pvr.mythtv it works without problems.

Another question: Is there a reason why all the pvr add-ons are defined in this single spec-file instead of one for each add-on?

**Comment by kuboosoft** [comment]
@mjanser can you test if the issue was solved?

```
su
dnf clean all && dnf -y update
```

**Comment by mjanser** [comment]
@kuboosoft thanks for the update. But I still have the same behaviour, kodi crashes when activating the add-on.

**Comment by kuboosoft** [comment]
mmm @mjanser can you help us? Do you used the current commit?

**Comment by mjanser** [comment]
I installed `kodi-pvr-mythtv-17.0-7.fc25.x86_64` from the repository. Unfortunately I don't see anything in the logs and it also doesn't create a crashlog. Kodi just crashes hard when I click the activate button of the add-on...

When installing the add-on manually as described at https://github.com/kodi-pvr/pvr.mythtv#linux it works without problems.

**Comment by kuboosoft** [comment]
@mjanser ok, I will make some changes, because it needs the source code of kodi for build... very strange. We generate the tarball with https://github.com/UnitedRPMs/kodi-pvr-addons/blob/master/kodi-pvr-addons-snapshot.sh

**Comment by kuboosoft** [comment]
@mjanser can you test with the new kodi?

**Comment by mjanser** [comment]
I tested it with `kodi-1:17.3-1.git147cec4.fc25.x86_64` and `kodi-pvr-mythtv-17.0-7.fc25.x86_64` now, but still the same behaviour.

**Comment by kuboosoft** [comment]
Do you have experience making rpm? you can help us to separate the kodi-pvr-mythtv... Generally I only use the iptv addon...You have an experience compiling in another way :)

**Comment by mjanser** [comment]
I don't have experience with making rpms but I can try it :) Probably only next week though.

**Comment by kuboosoft** [comment]
I can help you, isn't complicated...

**Comment by mjanser** [comment]
Unfortunately I can't get it to work. I tried different ways of building the rpm, but kodi always crashes when enabling the add-on. Could it be that some files or linked libraries are there during building but not on the target machine anymore? Because when I build it from sources on the target machine, they are still available on the system, and this works then.

**Comment by kuboosoft** [comment]
It only requires: zlib, kodi, kodi-platform, platform, cmake
Question, is it uses mythtv?

**Comment by mjanser** [comment]
After some more trying and researching it seems to work now. I think removing the flag `-DUSE_LTO=1` from cmake fixes the build, otherwise there were some errors saying `plugin needed to handle lto object`. I have no clue what this flag does and how to make it work with the enabled flag :)

Here the specfile I used for testing as a reference:
```specfile
Name:           kodi-pvr-mythtv
Version:        4.15.0
Release:        1%{?dist}
Summary:        Kodi PVR add-on for MythTV

Group:          Applications/Multimedia
License:        GPLv3 and GPLv2+ and LGPLv2+ and MIT
URL:            https://github.com/janbar/pvr.mythtv
Source0:        https://github.com/janbar/pvr.mythtv/archive/4.15.0.tar.gz

BuildRequires:  cmake
BuildRequires:  gcc
BuildRequires:  gcc-c++
BuildRequires:  zlib-devel
BuildRequires:  kodi-devel >= 17
BuildRequires:  platform-devel
BuildRequires:  kodi-platform-devel
BuildRequires:  cppmyth-devel
Requires:       kodi >= 17.0

%description
MythTV PVR add-on for Kodi.

%prep
%setup -T -b 0 -n pvr.mythtv-%{version}

%build
mkdir -p build/
cd build/
cmake -DCMAKE_INSTALL_PREFIX=%{_prefix} -DCMAKE_INSTALL_LIBDIR=%{_libdir} -DBUILD_SHARED_LIBS=1 ..
make

%install
cd build/
export PKG_CONFIG_PATH=%{_sourcedir}:%{_libdir}/pkgconfig
make install DESTDIR=%{buildroot}

%files
%{_libdir}/kodi/addons/pvr.mythtv/
%{_datadir}/kodi/addons/pvr.mythtv/
```

**Comment by kuboosoft** [comment]
mmmm, I will check if it build in F24-F27 without -DUSE_LTO=1 ; can you help us to maintain our kodi-pvr-addons? I can add you to team fastly :)

**Comment by mjanser** [comment]
ok, thank you! Sure, I can help you where I can :)

**Comment by kuboosoft** [comment]
Great! then, Welcome!!!, please accept the invitation and read our [wiki](https://github.com/UnitedRPMs/WIKI/wiki) :)

**Comment by kuboosoft** [comment]
@mjanser you found the problem!!! your task solved the problem, Can you update the spec file with 
your authorship and the change? remember fill the changelog with your data, also add a new release. thanks

`Release:        1%{?dist}`

to

`Release:        2%{?dist}`

```
%changelog

* Wed Jun 14 2017 your name last... <your email AT foo DOT com> - 17.2-2
- ....... fix.....
```

**Comment by mjanser** [comment]
I created a pull request #5, can you quickly check?

**Comment by kuboosoft** [comment]
@mjanser https://travis-ci.org/UnitedRPMs/kodi-pvr-addons ;  remember our unibuild tool+travis, test it for us :)

**Comment by mjanser** [comment]
Cool, it works now. Thank you!

**Comment by kuboosoft** [comment]
Is your fix ;)
